/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author aamir
 */
public class comboDate extends javax.swing.JPanel {

    /**
     * Creates new form comboDate
     */
    public comboDate() {
        initComponents();
        initDate();
    }
    public String getDate(){
        String s = "";
        String ts = "" + jSpinner3.getValue();
        int t = Integer.parseInt(ts);
        s = s + t + "-";
        ts = "" + jSpinner2.getValue();
        t = Integer.parseInt(ts);
        if (t < 10){
            s = s + "0" + t;
        }
        else {
            s = s + t;
        }
        s = s + "-";
        ts = "" + jSpinner1.getValue();
        t = Integer.parseInt(ts);
        if (t < 10){
            s = s + "0" + t;
        }
        else {
            s = s + t;
        }
        return s;
    }
    
    public void initDate(){
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = null;
        String y;
        int i;
        dateFormat = new SimpleDateFormat("dd");
        y = dateFormat.format( currentDate );
        i = Integer.parseInt(y);
        jSpinner1.setValue(i);
        dateFormat = new SimpleDateFormat("MM");
        y = dateFormat.format( currentDate );
        i = Integer.parseInt(y);
        jSpinner2.setValue(i);
        dateFormat = new SimpleDateFormat("y");
        y = dateFormat.format( currentDate );
        i = Integer.parseInt(y);
        jSpinner3.setValue(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();

        jSpinner1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    // End of variables declaration//GEN-END:variables
}
