/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Andrey
 */
public class EditForm extends javax.swing.JFrame {
    Form ob;
    String oldLName;
    String oldFName;
    String oldMName;
    public JTextField lName =new JTextField();
    public JTextField fName =new JTextField();
    public JTextField mName =new JTextField();
    String q;
    int id;
    /**
     * Creates new form EditForm
     */
    public EditForm(Form form, String ln, String fn, String mn) {
        ob = form;
        oldLName = ln;
        oldFName = fn;
        oldMName = mn;
        initComponents();
        lName.setBounds(10, 10, 120, 30);
        fName.setBounds(10, 50, 120, 30);
        mName.setBounds(10, 90, 120, 30);
        add(this.lName);
        add(this.fName);
        add(this.mName);
        lName.setText(ln);
        fName.setText(fn);
        mName.setText(mn);
        revalidate();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Checks.notEmpTeacher(lName.getText(), fName.getText(), mName.getText())){
            q = "UPDATE  `teachers` SET  `lName` =  '" + lName.getText() + "', "
                + "`fname` = '" + fName.getText() + "', "
                + "`mName` = '" + mName.getText() + "' "
                + "WHERE  `lname` ='" + oldLName + "' "
                + "AND `fname` ='" + oldFName + "' "
                + "AND`mname` ='" + oldMName + "';";
            System.out.println(q);
            DB d = new DB();
            try {
                d.delUpdate(q);
            } catch (SQLException ex) {
                Logger.getLogger(EditForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            ob.refTab();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
