@startuml
top to bottom direction
skinparam headerFontSize 30
skinparam headerFontStyle bold
skinparam classAttributeIconSize 0
scale 1.0
package DB {
class DB.MainDB <? extends DB>  {
.. Methods ..
+del(String, String) : void
+delUpdate(String) : void
+getBoxList(String, String, String) : String[]
+getBoxList(String, String) : String[]
+getTab(String, String) : String[][]
+getTab(String) : String[][]
+ins(String) : void
.. Static ..
+ {static} test() : boolean
}
class DB.SheduleDB <? extends DB>  {
.. Methods ..
+getArrAvailableShedule(String, String) : String[][]
+getArrDisciplines(String[][]) : String[][]
+getArrLoads(String) : String[][]
+getArrTeachers(String[][]) : String[][]
+getGroupId(String) : String
+isAvailableShedule(String, String) : boolean
}
class DB.DB {
.. Fields  ..
~rs : ResultSet
~stmt : Statement
.. Methods ..
.. Static ..
~ {static} closeCon() : void
~ {static} conn : Connection
~ {static} password : String
~ {static} url : String
~ {static} userName : String
}

}
package TeacherLoad {
class TeacherLoad.infoPanel {
.. Fields  ..
-jLabel1 : JLabel
-jLabel2 : JLabel
-jLabel3 : JLabel
.. Methods ..
-initComponents() : void
}
class TeacherLoad.hoursPanel {
.. Fields  ..
-jLabel1 : JLabel
-jLabel2 : JLabel
-jLabel3 : JLabel
-jLabel4 : JLabel
-jLabel5 : JLabel
-jLabel6 : JLabel
.. Methods ..
-initComponents() : void
}
class TeacherLoad.Form {
.. Fields  ..
-jLabel1 : JLabel
-jLabel2 : JLabel
-jLabel3 : JLabel
.. Methods ..
-initComponents() : void
.. Static ..
+ {static} main() : void
}

}
package gui {
class gui.EditForm {
.. Fields  ..
+fName : JTextField
~id : int
-jButton1 : JButton
+lName : JTextField
+mName : JTextField
~oldFName : String
~oldLName : String
~oldMName : String
~panel : Teacher
~q : String
.. Methods ..
-initComponents() : void
-jButton1ActionPerformed(ActionEvent) : void
}
class gui.main {
.. Methods ..
.. Static ..
+ {static} main() : void
}
class gui.Checks {
.. Methods ..
.. Static ..
+ {static} notEmpDiscipline() : boolean
+ {static} notEmpGroup() : boolean
+ {static} notEmpSpecialty() : boolean
+ {static} notEmpTeacher() : boolean
+ {static} notEmpTeacherLoad() : boolean
+ {static} testConnect() : boolean
}

}
package model {
class model.MyTable {
.. Fields  ..
~v : String[][]
.. Methods ..
~getData(String, String[]) : void
}
class model.LoadsForGroup {
.. Fields  ..
~arrDisciplines : String[][]
~arrLoads : String[][]
~arrTeachers : String[][]
.. Methods ..
+getArrDisciplines() : String[]
+getArrTeacherForDiscipline(String) : String[]
+getDisciplineId(String) : String
+getDisciplineNameOnId(String) : String
+getDisciplineOnTeacherLoadId(String) : String
+getGroupId() : String
+getLNameTeacherOnId(String) : String
+getLNameTeacherOnTeacherLoadId(String) : String
+getStringOfTeacherLoadsId() : String
+getTeacherId(String) : String
+getTeacherLoadId(String, String) : String
+setArrDisciplines() : void
+setArrLoads() : void
+setArrTeachers() : void
+setGroupId(String) : void
.. Static ..
~ {static} groupId : String
}

}
package shedule {
class shedule.AvailableShedule {
.. Fields  ..
~AvailableShedule : String[][]
~date : String
~shedule : Shedule
.. Methods ..
~setAvailableLesson(String[]) : void
~setAvailableShedule() : void
}
class shedule.LessonPanel {
.. Fields  ..
~arrToInsert : String[][]
+check : JCheckBox
-label : JLabel
~number : int
+subGroupI : JComboBox
+subGroupII : JComboBox
+teacherI : JComboBox
+teacherII : JComboBox
.. Methods ..
-checkActionPerformed(ActionEvent) : void
+getArrToInsert() : String[][]
-initComponents() : void
+isNotEmptyLesson(JComboBox) : boolean
+resetLesson() : void
+selectDiscipline(JComboBox, JComboBox) : void
+setDisciplinesBox() : void
+setLesson(String, String, String) : void
+setNumber(int) : void
+setTotalLesson() : void
+setValueOfArrToInsert(int, String, Object, Object) : void
-subGroupIActionPerformed(ActionEvent) : void
-subGroupIIActionPerformed(ActionEvent) : void
-subGroupIIPopupMenuWillBecomeInvisible(PopupMenuEvent) : void
-subGroupIPopupMenuCanceled(PopupMenuEvent) : void
-subGroupIPopupMenuWillBecomeInvisible(PopupMenuEvent) : void
-subGroupIPopupMenuWillBecomeVisible(PopupMenuEvent) : void
}
class shedule.Shedule {
.. Fields  ..
~AvailableShedule : String[][]
~arrLessonPanels : LessonPanel[]
~arrToInsert : String[][]
~available : AvailableShedule
+comboDate : comboDate
+groupShedule : JComboBox
-jButton1 : JButton
-jButton2 : JButton
-jButton8 : JButton
-jLabel4 : JLabel
-jLabel5 : JLabel
-lessonP1 : LessonPanel
-lessonP2 : LessonPanel
-lessonP3 : LessonPanel
-lessonP4 : LessonPanel
-lessonP5 : LessonPanel
.. Methods ..
+addShedule() : void
~getQuaryToInsert() : String
-groupShedulePopupMenuWillBecomeInvisible(PopupMenuEvent) : void
-groupShedulePopupMenuWillBecomeVisible(PopupMenuEvent) : void
+initArrLessons() : void
+initArrToInsert() : void
-initComponents() : void
-jButton1ActionPerformed(ActionEvent) : void
-jButton2ActionPerformed(ActionEvent) : void
-jButton8ActionPerformed(ActionEvent) : void
~resetLessons() : void
~selectGroup() : void
~setGroupsBox() : void
+setLesson(String, int, String, String) : void
.. Static ..
+ {static} loads : LoadsForGroup
}
class shedule.comboDate {
.. Fields  ..
-jSpinner1 : JSpinner
-jSpinner2 : JSpinner
-jSpinner3 : JSpinner
.. Methods ..
+getDate() : String
-initComponents() : void
+initDate() : void
}

}
package tabs {
class tabs.Discipline {
.. Fields  ..
-addDisciplineButton : JButton
+fName : JTextField
~fullName : String
-jButton1 : JButton
-jLabel1 : JLabel
-jLabel2 : JLabel
-jScrollPane2 : JScrollPane
+jTable2 : JTable
+sName : JTextField
~shortName : String
.. Methods ..
+addDiscipline() : void
-addDisciplineButtonActionPerformed(ActionEvent) : void
+delDiscipline() : void
-initComponents() : void
-jButton1ActionPerformed(ActionEvent) : void
+refTab() : void
}
class tabs.Specialty {
.. Fields  ..
+codeSpec : JTextField
~codeSpecialty : String
-jButton2 : JButton
-jButton3 : JButton
-jLabel6 : JLabel
-jLabel7 : JLabel
-jScrollPane3 : JScrollPane
+jTable3 : JTable
+nameSpec : JTextField
~nameSpecialty : String
.. Methods ..
+addSpecialty() : void
+delSpecialty() : void
-initComponents() : void
-jButton2ActionPerformed(ActionEvent) : void
-jButton3ActionPerformed(ActionEvent) : void
+refTab() : void
}
class tabs.TeacherLoad {
.. Fields  ..
+comboDiscipline : JComboBox
+comboFName : JComboBox
+comboGroup : JComboBox
+comboLName : JComboBox
+comboMName : JComboBox
~discipline : String
~fName : String
~group : String
-jButton1 : JButton
-jButton5 : JButton
-jButton7 : JButton
-jLabel10 : JLabel
-jLabel11 : JLabel
-jLabel12 : JLabel
-jScrollPane5 : JScrollPane
+jTable5 : JTable
~lName : String
~mName : String
.. Methods ..
+addTeacherLoad() : void
-comboGroupPopupMenuWillBecomeVisible(PopupMenuEvent) : void
+delTeacherLoad() : void
~getDisciplineList() : void
~getLFMNameList() : void
-initComponents() : void
-jButton5ActionPerformed(ActionEvent) : void
-jButton7ActionPerformed(ActionEvent) : void
+refTab() : void
~setGroupsBox() : void
}
class tabs.Group {
.. Fields  ..
~idSpecialty : String
-jButton4 : JButton
-jButton6 : JButton
-jLabel8 : JLabel
-jLabel9 : JLabel
-jScrollPane4 : JScrollPane
+jTable4 : JTable
~nameGroup : String
+nameGroupEdit : JTextField
+nameSpecOfGroup : JComboBox
~nameSpecialty : String
.. Methods ..
+addGroup() : void
+delGroup() : void
~getSpecialtyList() : void
-initComponents() : void
-jButton4ActionPerformed(ActionEvent) : void
-jButton6ActionPerformed(ActionEvent) : void
-nameSpecOfGroupPopupMenuWillBecomeVisible(PopupMenuEvent) : void
+refTab() : void
}
class tabs.Teacher {
.. Fields  ..
-addTeacher : JButton
-editTeacher : JButton
~fName : String
+fNameTeacher : JTextField
-jButton1 : JButton
-jScrollPane1 : JScrollPane
+jTable1 : JTable
~lName : String
+lNameTeacher : JTextField
~mName : String
+mNameTeacher : JTextField
-Имя : JLabel
-Отчество : JLabel
-Фамилия : JLabel
.. Methods ..
~addTeacher() : void
-addTeacherActionPerformed(ActionEvent) : void
~delTeacher() : void
~editTeacher() : void
-editTeacherActionPerformed(ActionEvent) : void
-initComponents() : void
-jButton1ActionPerformed(ActionEvent) : void
~refTab() : void
}

}
package view {
class view.Filer {
.. Methods ..
.. Static ..
+ {static} read() : String
+ {static} write() : void
- {static} exists() : void
}

}
DB.DB <|-- DB.MainDB
DB.DB <|-- DB.SheduleDB
gui.EditForm o-- "1..1" tabs.Teacher
shedule.Shedule *-- "0..*" shedule.LessonPanel
shedule.Shedule o-- "1..1" model.LoadsForGroup
shedule.Shedule o-- "1..1" shedule.comboDate
shedule.Shedule o-- "5..5" shedule.LessonPanel
shedule.AvailableShedule "1..1" o..o "1..1" shedule.Shedule
@enduml
