/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package shedule;

import javax.swing.JComboBox;
import static shedule.Shedule.loads;

/**
 *
 * @author aamir
 */
public class LessonPanel extends javax.swing.JPanel {
    String[][] arrToInsert = new String[2][3];
    int number;
    
    public LessonPanel() {
        initComponents();
    }
    public void setNumber(int n){
        number = n;
        label.setText(number + ".");
    }
    
    public void setDisciplinesBox(){
        subGroupI.removeAllItems();
        subGroupII.removeAllItems();
            
        subGroupI.addItem("");
        subGroupII.addItem("");

        for (String discipline: loads.getArrDisciplines()){          
            subGroupI.addItem(discipline);
            subGroupII.addItem(discipline);
        }
    }
    
    public void selectDiscipline(JComboBox teacher, JComboBox discipline){
        teacher.removeAllItems();
        for (String lName: loads.getArrTeacherForDiscipline((String)discipline.getSelectedItem())){
            teacher.addItem(lName);
        }        
    }
    
    public void setTotalLesson(){
        if (check.isSelected()){
            subGroupII.setEnabled(false);
        }
        else{
            subGroupII.setEnabled(true);
        }
        
    }
    
    public String[][] getArrToInsert(){
            if (check.isSelected()){
                if (isNotEmptyLesson(subGroupI)){
                    setValueOfArrToInsert(0, "", subGroupI.getSelectedItem(), teacherI.getSelectedItem());
                }
            }
            else{
                if (isNotEmptyLesson(subGroupI)){
                    setValueOfArrToInsert(0, "I", subGroupI.getSelectedItem(), teacherI.getSelectedItem());
                }
                if (isNotEmptyLesson(subGroupII)){
                    setValueOfArrToInsert(1, "II", subGroupII.getSelectedItem(), teacherII.getSelectedItem());
                }
            }
        return arrToInsert;
    }
    
    public void setValueOfArrToInsert(int i, String type, Object discipline, Object lName){
        arrToInsert[i][0] = "" + number;
                    arrToInsert[i][1] = type;
                    arrToInsert[i][2] = loads.getTeacherLoadId((String)lName, (String) discipline);
    }

    public boolean isNotEmptyLesson(JComboBox discipline){
        String v = (String) discipline.getSelectedItem();
        return !(v.equals(""));
    }
    
    public void setLesson(String type, String discipline, String lName){
        switch (type){
            case "":
                check.setSelected(true);
                subGroupI.setSelectedItem(discipline);
                teacherI.setSelectedItem(lName);
                break;
            case "I":
                check.setSelected(false);
                subGroupI.setSelectedItem(discipline);
                teacherI.setSelectedItem(lName);
                break;
            case "II":
                check.setSelected(false);
                subGroupII.setSelectedItem(discipline);
                teacherII.setSelectedItem(lName);
                break;
        }
        setTotalLesson();
    }

    public void resetLesson(){
        subGroupI.setSelectedItem("");
        subGroupII.setSelectedItem("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        subGroupI = new javax.swing.JComboBox();
        subGroupII = new javax.swing.JComboBox();
        teacherII = new javax.swing.JComboBox();
        teacherI = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(430, 70));

        label.setText("1.");

        check.setSelected(true);
        check.setText("общ.");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        subGroupI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        subGroupI.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                subGroupIPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                subGroupIPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                subGroupIPopupMenuWillBecomeVisible(evt);
            }
        });
        subGroupI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subGroupIActionPerformed(evt);
            }
        });

        subGroupII.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        subGroupII.setEnabled(false);
        subGroupII.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                subGroupIIPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        subGroupII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subGroupIIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(subGroupII, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subGroupI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherII, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(subGroupI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subGroupII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        setTotalLesson();
    }//GEN-LAST:event_checkActionPerformed

    private void subGroupIPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subGroupIPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_subGroupIPopupMenuWillBecomeInvisible

    private void subGroupIIPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subGroupIIPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_subGroupIIPopupMenuWillBecomeInvisible

    private void subGroupIPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subGroupIPopupMenuCanceled
        // TODO add your handling code here:
        
    }//GEN-LAST:event_subGroupIPopupMenuCanceled

    private void subGroupIPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subGroupIPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        
    }//GEN-LAST:event_subGroupIPopupMenuWillBecomeVisible

    private void subGroupIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subGroupIActionPerformed
        selectDiscipline(teacherI, subGroupI);
    }//GEN-LAST:event_subGroupIActionPerformed

    private void subGroupIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subGroupIIActionPerformed
        selectDiscipline(teacherII, subGroupII);
    }//GEN-LAST:event_subGroupIIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox check;
    private javax.swing.JLabel label;
    public javax.swing.JComboBox subGroupI;
    public javax.swing.JComboBox subGroupII;
    public javax.swing.JComboBox teacherI;
    public javax.swing.JComboBox teacherII;
    // End of variables declaration//GEN-END:variables
}
